services:
  backend:
    build: ./backend
    ports:
      - "3001:80"
    networks:
      - shiftsync-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - shiftsync-network

networks:
  shiftsync-network:
    driver: bridge
